version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
       - "8222:8222"
  client-gateway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    volumes: 
      - ./client-gateway/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}

  products-service:
    build: ./product-service
    volumes: 
      - ./product-service/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db
    
  orders-service:
    depends_on:
      - orders-db
    build: ./order-service
    volumes:
      - ./order-service/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
      - NATS_SERVERS=${NATS_SERVERS}

  orders-db:
      # container_name: orders-db
      image: postgres:16.2
      restart: always
      volumes:
        - orders_postgres_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=ordersdb
  supplier-service:
    depends_on:
      - supplier-service-db
      - nats-server
    build: ./supplier-go-service
    working_dir: /app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=supplier-service-db
      - DB_PORT=3306
      - DB_NAME=supplierdb
      - DB_USERNAME=root
      - DB_PASSWORD=dev_password
      - NATS_SERVERS=${NATS_SERVERS}
    
  supplier-service-db:
    image: mysql:8.0.42
    # container_name: supplier-service-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev_password
      MYSQL_DATABASE: supplierdb
    volumes:
      - supplier_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    
  payments-service:
    build: ./payment-service
    volumes: 
      - ./payment-service/src:/usr/src/app/src
    command: yarn start:dev
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    environment:
      - PORT=${PAYMENT_SERVICE_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - NATS_SERVERS=${NATS_SERVERS}
  auth-service:
    build: ./auth-service
    volumes: 
      - ./auth-service/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=${NATS_SERVERS}
volumes:
  supplier_mysql_data:
  orders_postgres_data: